swagger: "2.0"
info:
    title: Task Service
    description: The task service is executing tasks created from policies.
    version: 0.0.1
host: localhost:8082
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /liveness:
        get:
            tags:
                - health
            summary: Liveness health
            operationId: health#Liveness
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HealthResponse'
                        required:
                            - service
                            - status
                            - version
            schemes:
                - http
    /readiness:
        get:
            tags:
                - health
            summary: Readiness health
            operationId: health#Readiness
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HealthResponse'
                        required:
                            - service
                            - status
                            - version
            schemes:
                - http
    /v1/task/{taskName}:
        post:
            tags:
                - task
            summary: Create task
            description: Create a task and put it in a queue for execution.
            operationId: task#Create
            parameters:
                - name: taskName
                  in: path
                  description: Task name.
                  required: true
                  type: string
                - name: x-cache-namespace
                  in: header
                  description: Cache key namespace
                  required: false
                  type: string
                - name: x-cache-scope
                  in: header
                  description: Cache key scope
                  required: false
                  type: string
                - name: any
                  in: body
                  description: Data contains JSON payload that will be used for task execution.
                  required: true
                  schema: {}
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/CreateTaskResult'
                        required:
                            - taskID
            schemes:
                - http
    /v1/taskList/{taskListName}:
        post:
            tags:
                - taskList
            summary: Create taskList
            description: Create a task list and corresponding tasks and put them in respective queues for execution.
            operationId: taskList#Create
            parameters:
                - name: taskListName
                  in: path
                  description: TaskList name.
                  required: true
                  type: string
                - name: x-cache-namespace
                  in: header
                  description: Cache key namespace
                  required: false
                  type: string
                - name: x-cache-scope
                  in: header
                  description: Cache key scope
                  required: false
                  type: string
                - name: any
                  in: body
                  description: Data contains JSON payload that will be used for taskList execution.
                  required: true
                  schema: {}
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/CreateTaskListResult'
                        required:
                            - taskListID
            schemes:
                - http
    /v1/taskListStatus/{taskListID}:
        get:
            tags:
                - taskList
            summary: TaskListStatus taskList
            description: TaskListStatus retrieves a taskList status containing all tasks' unique IDs and statuses from the Cache service.
            operationId: taskList#TaskListStatus
            parameters:
                - name: taskListID
                  in: path
                  description: Unique taskList identifier.
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TaskListStatusResponse'
                        required:
                            - id
                            - status
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/TaskListStatusResponse'
                        required:
                            - id
                            - status
                "202":
                    description: Accepted response.
                    schema:
                        $ref: '#/definitions/TaskListStatusResponse'
                        required:
                            - id
                            - status
                "207":
                    description: Multi-Status response.
                    schema:
                        $ref: '#/definitions/TaskListStatusResponse'
                        required:
                            - id
                            - status
            schemes:
                - http
    /v1/taskResult/{taskID}:
        get:
            tags:
                - task
            summary: TaskResult task
            description: TaskResult retrieves task result from the Cache service.
            operationId: task#TaskResult
            parameters:
                - name: taskID
                  in: path
                  description: Unique task identifier.
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema: {}
            schemes:
                - http
definitions:
    CreateTaskListResult:
        title: CreateTaskListResult
        type: object
        properties:
            taskListID:
                type: string
                description: Unique taskList identifier.
                example: Amet sapiente qui non.
        example:
            taskListID: Sint nulla.
        required:
            - taskListID
    CreateTaskResult:
        title: CreateTaskResult
        type: object
        properties:
            taskID:
                type: string
                description: Unique task identifier.
                example: Excepturi non.
        example:
            taskID: Ut et est aut quae magnam.
        required:
            - taskID
    GroupStatus:
        title: GroupStatus
        type: object
        properties:
            id:
                type: string
                description: Unique group identifier.
                example: a7d1349d-34b5-4c65-b671-d1aa362fc446
            status:
                type: string
                description: Current status of the group
                example: done
            tasks:
                type: array
                items:
                    $ref: '#/definitions/TaskStatus'
                description: Array of TaskStatus
                example:
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
        example:
            id: a7d1349d-34b5-4c65-b671-d1aa362fc446
            status: done
            tasks:
                - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                  status: done
                - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                  status: done
                - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                  status: done
    HealthResponse:
        title: HealthResponse
        type: object
        properties:
            service:
                type: string
                description: Service name.
                example: Totam dolores voluptas laudantium incidunt.
            status:
                type: string
                description: Status message.
                example: Eaque velit fugit ut eius sint earum.
            version:
                type: string
                description: Service runtime version.
                example: Doloremque earum aliquid ipsa.
        example:
            service: Voluptas odit voluptate nobis nam quia quae.
            status: Maxime facilis.
            version: Laboriosam cumque.
        required:
            - service
            - status
            - version
    TaskListStatusResponse:
        title: TaskListStatusResponse
        type: object
        properties:
            groups:
                type: array
                items:
                    $ref: '#/definitions/GroupStatus'
                description: Array of GroupStatus
                example:
                    - id: a7d1349d-34b5-4c65-b671-d1aa362fc446
                      status: done
                      tasks:
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                    - id: a7d1349d-34b5-4c65-b671-d1aa362fc446
                      status: done
                      tasks:
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                    - id: a7d1349d-34b5-4c65-b671-d1aa362fc446
                      status: done
                      tasks:
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                    - id: a7d1349d-34b5-4c65-b671-d1aa362fc446
                      status: done
                      tasks:
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
                        - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                          status: done
            id:
                type: string
                description: Unique taskList identifier.
                example: 9cc9f504-2b7f-4e24-ac59-653e9533840a
            status:
                type: string
                description: Current status of the taskList
                example: done
        example:
            groups:
                - id: a7d1349d-34b5-4c65-b671-d1aa362fc446
                  status: done
                  tasks:
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                - id: a7d1349d-34b5-4c65-b671-d1aa362fc446
                  status: done
                  tasks:
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                - id: a7d1349d-34b5-4c65-b671-d1aa362fc446
                  status: done
                  tasks:
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
                    - id: d16996cd-1977-42a9-90b2-b4548a35c1b4
                      status: done
            id: 9cc9f504-2b7f-4e24-ac59-653e9533840a
            status: done
        required:
            - id
            - status
    TaskStatus:
        title: TaskStatus
        type: object
        properties:
            id:
                type: string
                description: Unique task identifier.
                example: d16996cd-1977-42a9-90b2-b4548a35c1b4
            status:
                type: string
                description: Current status of the task
                example: done
        example:
            id: d16996cd-1977-42a9-90b2-b4548a35c1b4
            status: done
